### ISSUE TITLE
Package rename from "compton" to "picom"

### ISSUE THREAD

**Issue by tiritto** [regolith-linux/speed-ricer#9] opened 2020-01-23 03:56 UTC
I believe that it might be appropriate to rename "compton" package to "picom". Such change would make it clear right away that the provided package is a maintained fork of Compton rather than old Compton. On top of avoiding general versioning confusion, I believe it will also somehow help out Picom maintainers by making people more aware of Picom presence as de facto Compton successor.

**Comment by kgilmer** [comment] 2020-01-27 02:23
Hi @tiritto, I'm being lazy and waiting for a new version that actually has something to offer other than the name change.

**Comment by moritzheiber** [comment] 2020-05-24 08:49
Closing this as a duplicate of https://github.com/regolith-linux/regolith-desktop/issues/419

**Closed by moritzheiber** 2020-05-24 08:49 UTC
Labels: duplicate
