### ISSUE TITLE
Update polybar version

### ISSUE THREAD

**Issue by aacebedo** [regolith-linux/speed-ricer#4] opened 2019-10-06 06:50 UTC
Polybar 3.4.0 has been released but in the PPA we still have 3.3.0.

Can you update it ?

Thanks !

**Comment by appelgriebsch** [comment] 2019-10-06 10:11
you can find an updated version here: https://github.com/appelgriebsch/polybar/releases/tag/3.4.0

**Comment by aacebedo** [comment] 2019-10-06 10:27
Thanks ! I am going to install it.

In the end it will be even better to have it in the PPA to ease the update

**Comment by moritzheiber** [comment] 2020-05-24 08:50
Closing this a duplicate of #12

**Closed by moritzheiber** 2020-05-24 08:50 UTC
Labels: duplicate
